version: "2"
services:

  agency1: 
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.endpoint tcp://0.0.0.0:8529 --agency.my-address tcp://agency1:8529 --server.authentication false --agency.size 3 --agency.activate true --agency.supervision true --agency.endpoint tcp://agency1:8529 --agency.endpoint tcp://agency2:8529 --agency.endpoint tcp://agency3:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./logs/a1:/var/log/arangodb3

  agency2:
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.endpoint tcp://0.0.0.0:8529 --agency.my-address tcp://agency2:8529 --server.authentication false --agency.size 3 --agency.activate true --agency.supervision true --agency.endpoint tcp://agency1:8529 --agency.endpoint tcp://agency2:8529 --agency.endpoint tcp://agency3:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./logs/a2:/var/log/arangodb3

  agency3:
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.endpoint tcp://0.0.0.0:8529 --agency.my-address tcp://agency3:8529 --server.authentication false --agency.size 3 --agency.activate true --agency.supervision true --agency.endpoint tcp://agency1:8529 --agency.endpoint tcp://agency2:8529 --agency.endpoint tcp://agency3:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./logs/a3:/var/log/arangodb3

  coordinator1:
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://coordinator1:8529 --cluster.my-local-info coord1  --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://agency1:8529 --cluster.agency-endpoint tcp://agency2:8529 --cluster.agency-endpoint tcp://agency3:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./data/c1:/var/lib/arangodb3
    - ./apps/c1:/var/lib/arangodb3-apps
    - ./logs/c1:/var/log/arangodb3
    ports: ['8001:8529']

  coordinator2:
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://coordinator2:8529 --cluster.my-local-info coord2  --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://agency1:8529 --cluster.agency-endpoint tcp://agency2:8529 --cluster.agency-endpoint tcp://agency3:8529  --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./data/c2:/var/lib/arangodb3
    - ./apps/c2:/var/lib/arangodb3-apps
    - ./logs/c2:/var/log/arangodb3
    ports: ['8002:8529']

  db1:
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://db1:8529 --cluster.my-local-info db1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://agency1:8529 --cluster.agency-endpoint tcp://agency2:8529 --cluster.agency-endpoint tcp://agency3:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./data/d1:/var/lib/arangodb3
    - ./logs/d1:/var/log/arangodb3

  db2:
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://db2:8529 --cluster.my-local-info db2 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://agency1:8529 --cluster.agency-endpoint tcp://agency2:8529 --cluster.agency-endpoint tcp://agency3:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./data/d2:/var/lib/arangodb3
    - ./logs/d2:/var/log/arangodb3

  db3:
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://db3:8529 --cluster.my-local-info db3 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://agency1:8529 --cluster.agency-endpoint tcp://agency2:8529 --cluster.agency-endpoint tcp://agency3:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./data/d3:/var/lib/arangodb3
    - ./logs/d3:/var/log/arangodb3
