version: "2"
services:

  coordinator2:
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://coordinator2:8529 --cluster.my-local-info coord2  --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://agency1:8529 --cluster.agency-endpoint tcp://agency2:8529 --cluster.agency-endpoint tcp://agency3:8529  --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./data/c2:/var/lib/arangodb3
    - ./apps/c2:/var/lib/arangodb3-apps
    - ./logs/c2:/var/log/arangodb3
    ports: ['8002:8529']
