version: "2"
services:

  db1:
    image: arangodb/arangodb
    environment:
    - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://db1:8529 --cluster.my-local-info db1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://agency1:8529 --cluster.agency-endpoint tcp://agency2:8529 --cluster.agency-endpoint tcp://agency3:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
    - ./data/d1:/var/lib/arangodb3
    - ./logs/d1:/var/log/arangodb3
